baseURL = 'https://fedora-riscv.github.io'
languageCode = 'zh-CN'
theme = 'diary'
title = 'Fedora-V Force'

ignoreFiles = ['README.md', 'LICENSE']

[params]
subtitle = '哆啦V盟'

[menu]

[[menu.main]]
url = "/"
name = "Home"
identifier = "home"
weight = 1

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

[[menu.main]]
url = "/fedora-riscv-devel-docs"
name = "Fedora-RISC-V Devel Docs"

[[menu.main]]
url = "/test-reports"
name = "Test Reports"